{
    "name": "Retenue à la Source",
    "version": "19.0.1.0.0",
    "summary": "Customer and vendor withholding workflow",
    "category": "Accounting",
    "author": "Digi-IT",
    "website": "https://digi-it.com.tn",
    "license": "LGPL-3",
    "depends": ["account"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/account_journal_views.xml",
        "views/account_tax_views.xml",
        "views/account_payment_views.xml",
        "views/account_payment_register_views.xml",
        "views/account_move_views.xml",
        "views/retenu_source_record_views.xml",
        "wizard/retenu_source_wizard_views.xml",
    ],
    "images": ["static/description/cover.png"],
    "installable": True,
    "application": False,
}