{
    'name':"Ebios Risk Manager",
    'author':"DIGI-IT",
    'category': 'Technical/Technical',
    'version' :'18.0.0.32',
    'author': 'DIGI-ERP',
    'website': 'https://digi-it.com.tn',
    'summary': 'Etudiez la  sécurité de votre environement conformement à la methode ebios_rm',
    'depends': ['base', 'hr', 'web'],
    'data':[
		'security/ebios_security.xml',
		'security/ir.model.access.csv',
		'data/default_template_data.xml',
		'data/sequence.xml',
		'views/base_menu.xml',
      	'views/stakeholder_views.xml',
		'views/study_view.xml',
		'views/study_object_view.xml',
		'views/iteration_view.xml',
		'views/business_value_view.xml',
		'views/local_view.xml',
		'views/data_view.xml',
		'views/application_view.xml',
		'views/material_paper_view.xml',
		'views/network_view.xml',
		'views/bv_description_activity_view.xml',
		'views/dreaded_event_view.xml',
		'views/risk_source_view.xml',
		'views/ecosystem_view.xml',
		'views/operational_scenario_view.xml',
		'views/risk_treatment_view.xml',
		'views/study_pacs_views.xml',
		'views/scale_seriousness_view.xml',
		'views/scale_impact_view.xml',
		'views/scale_impact_level_view.xml',
		'views/scale_impact_level_pivot_view.xml',
		'views/abstract_simple_scale_view.xml',
		'views/scale_likelihood_view.xml',
		'views/scale_risk_level_view.xml',
		'views/scale_threat_level_view.xml',
		'views/scale_risk_details_view.xml',
		'views/scale_stakeholder_threat_view.xml',
		'views/stakeholder_relationship_level_view.xml',
		'views/stakeholder_relationtionship_threat_pivot_view.xml',
		'views/actif_informationnel_classification_view.xml',
		'views/actif_informationnel_view.xml',
		'views/bien_support_view.xml',
		'views/named_model_view.xml',
		'views/motivation_view.xml',
		'views/ressource_view.xml',
		'views/activity_view.xml',
		'views/pertinence_view.xml',
		'views/matrix_view.xml',
		'views/pertinence_matrix_view.xml',
		'views/target_objective_view.xml',
		'views/risk_src_view.xml',
		'views/digiit_has_color_view.xml',
		'data/default_data.xml',
		'views/config_parameter.xml',
		'views/threat_level_limit_view.xml',
		'views/ebios_report_template_views.xml',
		'views/security_criteria_view.xml',
		'views/elementary_step_view.xml',
		'views/likelihood_value_view.xml',
		'views/gravity_value_view.xml',
		'views/risk_level_view.xml',
		'views/risk_level_matrix_view.xml',
		'views/visual_strategic_scenario_view.xml',
		'views/referentiel_views.xml',
		'views/application_status_scale_views.xml',
		'views/study_referentiel_views.xml'],
    'assets':{
        'web.assets_backend': [
            'digiit_ebios_rm/static/src/components/**/*',
			'digiit_ebios_rm/static/src/**/*',
			'digiit_ebios_rm/static/src/libs/html2canvas.min.js',
        ],
        'web.report_assets_common':[]
    },
	'images': ['static/description/cover.png'],
    'application': True,
    'installable': True,
	'license': 'LGPL-3',
}
