{
    "name": "Évaluation",
    "author": "Digi-ERP",
    "summary": "Module personnalisé d’évaluation du personnel",
    "description": """
    Module de gestion des évaluations des employés
    """,
    "version": "18.0.0.3",
    'website': 'https://digi-it.com.tn',
    "category": "Human Resources",
    "depends": ['base', 'hr','mail','survey','contacts'],
    "data": [
        "security/ir.model.access.csv",
        'security/appraisal_security.xml',
        "views/appraisal_views.xml",
        "views/appraisal_grid_views.xml",
        "views/template_views.xml",
        "views/setting_views.xml",
        "views/objective_view.xml",
        "views/report_view.xml",
        "views/appraisal_skills_views.xml",
        "views/skills_view.xml",
        "views/feedback_360.xml",
        "views/employee_views.xml",
        "data/appraisal_template_data.xml",
        'data/appraisal_grid_data.xml',
        'data/skills_data.xml',
        "data/objective_tags.xml",
        "data/survey_feedback_360_complete.xml",
        "views/appraisal_menu.xml",
    ],
    'images': ['static/description/cover.png'],
    "installable": True,
    "application": True,
    'license': 'LGPL-3',
}
